---
title: "Rapport de la ville"
format: "html"
author: "Adrien ALLAIN"
params: 
  code_commune: "44109"
  code_departement: "44"
---

```{r echo = FALSE, eval = TRUE, include=FALSE}
library(remotes)
library(firstlibAdrienALLAIN)
library(dplyr)
library(ggplot2)
library(lubridate)

data <- firstlibAdrienALLAIN::data
```


```{r echo = FALSE, eval = TRUE}
#Nom de la ville pour titre

nom_ville <- data |> 
  filter(Code.de.la.commune == params$code_commune, Code.du.département == params$code_departement) |> 
  pull(Libellé.de.la.commune) |> 
  unique()
```

```{r echo=FALSE}
cat("Rapport de la ville de", nom_ville, "\n")
```



```{r echo = FALSE, eval = TRUE}
# Paramètres
code_commune <- params$code_commune
code_departement <- params$code_departement

# Commune
df_commune <- data[
  data$Code.de.la.commune == code_commune & 
  data$Code.du.département == code_departement, ]

if (nrow(df_commune) > 0) {
  summary_commune(df_commune)
  plot_commune(df_commune)
}

# Département
df_departement <- data[
  data$Code.du.département == code_departement, ]

if (nrow(df_departement) > 0) {
  summary_departement(df_departement)
  plot_departement(df_departement)
}

```
